names:
  0: wrist
  1: thumb_tip
  2: thumb_ip
  3: thumb_mcp
  4: index_tip
  5: index_dip
  6: index_pip
  7: index_mcp
  8: middle_tip
  9: middle_dip
  10: middle_pip
  11: middle_mcp
  12: ring_tip
  13: ring_dip
  14: ring_pip
  15: ring_mcp
  16: pinky_tip
  17: pinky_dip
  18: pinky_pip
  19: pinky_mcp
  20: palm_center
path: ./data/hand_keypoints
test: images/test
train: images/train
val: images/val
