# 手のキーポイント検出用YOLO設定ファイル

# ベースモデル
model: yolo11n-pose.pt

# データセット設定
data: data/hand_keypoints/data.yaml

# 学習パラメータ
epochs: 100
batch: 16
imgsz: 640
device: 0  # GPU使用（CPUの場合は'cpu'に変更）

# 最適化設定
optimizer: AdamW
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# データ拡張
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0

# 学習設定
pretrained: true
cos_lr: true
close_mosaic: 10
amp: true
fraction: 1.0

# 保存設定
save: true
save_period: -1
cache: false
patience: 50

# ログ設定
project: runs/pose
name: hand_keypoints
exist_ok: false
plots: true
save_txt: false
save_json: false
save_hybrid: false
save_conf: false
save_crop: false

# その他
workers: 8
rect: false
resume: false
seed: 0
deterministic: true
single_cls: false
verbose: true