amp: true
batch: 16
cache: false
close_mosaic: 10
conf: 0.001
cos_lr: false
data: ./configs/dataset.yaml
degrees: 0.0
deterministic: true
device: auto
dropout: 0.0
epochs: 100
exist_ok: true
fliplr: 0.5
flipud: 0.0
fraction: 1.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
iou: 0.6
kpt_label: true
lr0: 0.01
lrf: 0.01
mask_ratio: 4
max_det: 300
mixup: 0.0
model: yolo11n-pose.pt
momentum: 0.937
mosaic: 1.0
name: hand_keypoints
optimizer: auto
overlap_mask: true
patience: 20
perspective: 0.0
plots: true
pretrained: true
project: ./runs
rect: false
save: true
save_period: 10
scale: 0.5
seed: 0
shear: 0.0
single_cls: false
task: pose
translate: 0.1
val: true
verbose: true
weight_decay: 0.0005
workers: 8
